### ISSUE TITLE
URL Scheme support?

### ISSUE THREAD

**Issue by jeffrey52** [thomasfinch/GammaThingy#10]
It would be awesome if the app could support URL schemes, so we can automate dimming with Workflow/Launch Center Pro!

(Disclosure: I'm not an iOS dev, no idea how easy this would be but I think it would be a perfect addition! Also, this would be a nice place to say: my eyes thank you for the app, it's great! :) )

**Comment by CasperCLD** [comment]
Sadly this not possible. URL schemes would redirect the user to the app 'GammaThingy'. Thus the app would open, and disrupt the flow. This is due the ['Sandbox'](https://developer.apple.com/app-sandboxing/) security which poses limits.

**Comment by jeffrey52** [comment]
Isn't that what [x-callback](http://x-callback-url.com) is for? So i.e. Workflow opens GammaThingy, GammaThingy enables/disables, and opens Workflow again.

**Comment by CasperCLD** [comment]
Hmm true that. [Looks](https://github.com/luuuke/GammaThingy/commit/acc3cc7f4e4b22460c2b364f2f42fb1adacbcce8) like @luuuke  is working on this. :+1:

**Comment by luuuke** [comment]
Yep, I've actually just added the x-callback thing. Not sure if it's implementation is perfect, though, as I'm really just checking if an x-source (the scheme of the "calling" app) is set. If that's the case it tries to open the app again.

**Comment by jeffrey52** [comment]
The URL scheme works great so far, but I can't get the x-source app to open again. I've tried the commented URL in the code, but unfortunately without success. The app just stays active and isn't redirecting back.

**Comment by luuuke** [comment]
Sounds great! Now just @thomasfinch has to merge it :)

**Comment by thomasfinch** [comment]
As far as I can tell all of these features were merged in https://github.com/thomasfinch/GammaThingy/commit/9535e1d3efd99a7d797958a1ef2f9b65c2997b23 so I'm closing this. Please reopen if I missed something.
