### ISSUE TITLE
Activating after reboot

### ISSUE THREAD

**Issue by ANGOmarcello** [thomasfinch/GammaThingy#27]
When enabled is set to 1 and you reboot and open Gamma Thingy again the enabled switch is active but the effect is not present.

Workaround:
Turning enabled off and on again does help for now.

Possible solution: 
Adding logic at application launch that checks for the state of enabled.

**Comment by thomasfinch** [comment]
It isn't possible to tell from the gamma table what color the screen is set to. Actually I should say it is but it would be a huge pain. If you have a solution for this you can send a pull request but until then I'm going to close this because there's no way for it to work.

**Comment by ANGOmarcello** [comment]
Calling `autoChangeOrangenessIfNeeded` in `application didFinishLaunchingWithOptions:` and adding the following to  `autoChangeOrangenessIfNeeded` works perfectly:

```if ([defaults boolForKey:@"enabled"]){
        [self enableOrangeness];
    }```

This brings following benefits:
-On launch the applications checks if it should be enabled. Means the actual state of the application matches it's user defaults again
-Background fetching wake will reenable gamma thingy after a reboot if no timer is set but enabled is set to on
Optional:
With my background implementation Gamma Thingy is reboot persistent and enabled 2-3 seconds after entering the home screen. (The battery thing is still in testing but we should note this benefit.)


I have a working implementation ready works even better then expected. I will create a pull request.

**Comment by thomasfinch** [comment]
Ah thank you, sorry I misunderstood.
