### ISSUE TITLE
Color Issues

### ISSUE THREAD

**Issue by gh0sti** [thomasfinch/GammaThingy#3]
Distorts color on iPhone 6s+, leaves green pixels and other distorted color.

**Comment by DotTheI** [comment]
Same on iPhone 6

**Comment by luuuke** [comment]
Could you try to make a picture of the problem and post it here?

**Comment by JosephDuffy** [comment]
I can confirm this also happens on an iPhone 6 running iOS 9.0. When taking a screenshot it doesn't capture the "distortion". It is worse with the option set on, but still present when off. I may be able to take a photo with my webcam tomorrow.

**Comment by DotTheI** [comment]
@luuuke It can't be captured by screen shots, so I made a picture with an "external" camera
![img_9594](https://cloud.githubusercontent.com/assets/10737439/10408163/593cd34a-6eab-11e5-9266-b001c6b59b3c.jpg)

**Comment by thomasfinch** [comment]
Can you try restarting your phone? That resets the colors and may fix it.

**Comment by DotTheI** [comment]
@thomasfinch Restarting didn't help

**Comment by Critter** [comment]
`Settings / General / Accessibility / Increase Contrast /`

Disable `Reduce White Point`

it worked for me. was mentioned by someone on reddit

**Comment by DotTheI** [comment]
@Critter I have it enabled. It might be the culprit. However, it would be just a workaround to turn it off.

**Comment by luuuke** [comment]
Oh wow, just tried it myself with reduced white point. Looks trippy. Seems to be an issue when two gamma table settings get mixed.

**Comment by DotTheI** [comment]
@thomasfinch
Has the issue been fixed?

**Comment by thomasfinch** [comment]
No, but it was clearly caused by reduced white point. The easy solution is to disable reduced white point, and that's orders of magnitude easier than digging into how that interacts with the gamma table to cause this problem. I don't have the time or knowledge of how the gamma table works to fix the root cause.
