### ISSUE TITLE
Add a proper license please

### ISSUE THREAD

**Issue by fileability** [thomasfinch/GammaThingy#30]
> I purposely have not added an open source license to the project and am intentionally retaining copyright for the code, meaning that it may not be redistributed (in code or compiled form) without my permission.

Here's a summary of the permissions already granted:

1. Others can view the code
2. Others can redistribute the code (via forking, as per GitHub's ToS)

Here's a summary of the permissions *not* granted:

1. Nobody is allowed to modify the code.
2. Nobody is allowed to compile the code.
3. Nobody is allowed to install the code on their device.
4. Nobody is allowed to run the code.

I realise you're being nice, but because there is no license agreement, it is not at all clear what you are and aren't allowing.

What I _think_ you want to do is allow everything except redistributing compiled binaries. Perhaps that is what you should say.

**Comment by thomasfinch** [comment]
You're right, I will change that. Thanks for pointing this out.

**Comment by cfilipov** [comment]
Perhaps using GPL would cover this? With GPL you prevent people from submitting it to the app store, but you can continue to share the source and keep it free.
