### ISSUE TITLE
Provide a fade transition when enabling or disabling gamma shift

### ISSUE THREAD

**Issue by jakezien** [thomasfinch/GammaThingy#31]
The lack of transition to oranginess is a bit jarring. When activating automatically, a gradual change à la flux would be ideal. When activating with the manual switch, a shorter fade would be nice. 

Thanks for the awesome app, by the way—you've checked off a feature that's been at the top of my wish list for years. I know Apple will never build it, but if they did, they'd give it a fancy marketing name (Natural Temperature) and claim to have invented it.

**Comment by ANGOmarcello** [comment]
This is indeed a thing that should be implemented at some point in my opinion.
But it could take time as Gamma Thingy is shaping up slowly. 

PS: Personally I would have no problem with apple implementing that in the future. :)

**Comment by ANGOmarcello** [comment]
@jakezien I have a branch with transitions on my fork you should try it out. :)
https://github.com/ANGOmarcello/GammaThingy/tree/Transition
