### ISSUE TITLE
No non-expired provisioning profiles were found?

### ISSUE THREAD

**Issue by athyman** [thomasfinch/GammaThingy#32]
Hello, 

I'm new to this so sorry if it is a stupid question, but when I open GammaTest.xcodeproj in Xcode 7.0.1, I get a yellow triangle with an exclamation point that said "Applications using launch screen files and targeting iOS 7.1 and earlier need to also include a launch image in an asset catalog." I have OSX 10.10.5 and am trying to install GammaThingy on an iOS 9.0.2 device. I also get another warning, an exclamation point in a stop sign, reading "No provisioning profiles found: No non-expired provisioning profiles were found." It then says "Failed to code sign" when I attempt to build on the device, prompting me to "Fix Issue". It goes through a loading screen and then says "An App ID with Identifier 'me.thomasfinch.GammaThingy' is not available. Please enter a different string." and does not complete the build. How can I resolve this issue? Thanks for your time and for building this.

**Comment by drewfer5** [comment]
https://www.youtube.com/watch?v=D_01P4-ubdA

**Comment by thomasfinch** [comment]
This is an issue with your account configuration in Xcode and not with the project itself. You should be able to find some information on how to fix the problem by googling it.

**Comment by athyman** [comment]
Cool. In case other people have this problem, all I had to do was add anything (in my case ".[username]") to the Bundle Identifier within "General", and it worked immediately.

**Comment by WyattLiu** [comment]
That ".username" works for me as well.

**Comment by theodoruszq** [comment]
@athyman Yeah, that's cool. It has solved my issue perfectly! Thanks!
