### ISSUE TITLE
How can it get colder rather than warmer?

### ISSUE THREAD

**Issue by xream** [thomasfinch/GammaThingy#36]
Thank you very much for your hard work!
I have an iPhone with warm screen which is warmer and white color shows like yellow.
With this app I can only make the screen warmer.
How can it get colder rather than warmer?

**Comment by xream** [comment]
```
    percentOrange = percentOrange / 10;
    NSLog(@"percentOrange: %f", percentOrange);
    if (percentOrange > 1)
        percentOrange = 1;
    else if (percentOrange < 0)
        percentOrange = 0;
    
    float blue = 1.0;
    float red = 1 - percentOrange;
    float green = (red + blue)/2.0;
```

I changed a little code and it works! Is this the best way to make it colder?

**Comment by thomasfinch** [comment]
That would work, or you could make it call the setGamma function directly with red, blue, and green percentages.
