### ISSUE TITLE
Automatic changing doesn't work in iPhone 5C and 4S

### ISSUE THREAD

**Issue by tjaadvd** [thomasfinch/GammaThingy#38]
The Automatic Color Changing doesn't work on my iPhone 5C and 4S. Could this have something to do with my location (The Netherlands)?

**Comment by ANGOmarcello** [comment]
It should work but unreliable so far. You sure it is not working at all or maybe working much later then specified?

**Comment by CasperCLD** [comment]
It only changes your screen temperature when your screen is active and iOS decides to do a background refresh, which is quite unreliable. I'm working on a solution for this. See #37

**Comment by NemuiStefan** [comment]
For me, it's not working either on my iPhone 6s. I mostly noticed 1 1/2 hours or so after it should switch. It sounds weird to me that iOS doesn't do a background refresh within that time frame even though I've been using it quite a lot.

**Comment by cfilipov** [comment]
@ANGOmarcello How's your VoIP branch going? I noticed you merged it in then removed it. I pulled it and seems to work better than background app refresh so far, are you experiencing issues?

**Comment by NemuiStefan** [comment]
I have an update: So this morning, it should have turned off at 7:00 am. At 9:12 am I opened the app, still enabled. Then I disabled and reenabled Automatic Color Changing and after reenabling it, it finally turned off. Maybe this can help you.

**Comment by luuuke** [comment]
Some time ago I logged for about 24 hours when the refresh triggers and it didn't work once in this time frame. When you read up about Background App Refresh it really sounds like it's really the wrong API to use for this case, as SpringBoard tries to apply way too much logic.

**Comment by tjaadvd** [comment]
For me, the Automatic Color Changing doesn't seems to do anything, even when the app is open and I switch it on and off. The color always changes to the Orange-ness

**Comment by ANGOmarcello** [comment]
I have no issues and my batterie is fine. :)

**Comment by tjaadvd** [comment]
I have tried the latest source but it does not automatically change in the evening. When I open the app it does change instantly so I am still very pleased with this app :D. Keep up the good work!

**Comment by jaggions** [comment]
> I have tried the latest source but it does not automatically change in the evening. When I open the app it does change instantly

Same here.

**Comment by drewfer5** [comment]
Ok so far no solution to automatically change color has worked. I'm forced to open the app and enable every evening.

**Comment by ANGOmarcello** [comment]
Could you try this? https://github.com/ANGOmarcello/GammaThingy/tree/VOIPBackgrounding

**Comment by tjaadvd** [comment]
Yes it works!

Verstuurd vanaf mijn iPhone

**Comment by ANGOmarcello** [comment]
@tjaadvd please report back in a few days so that we know how it affects your batterie life.

**Comment by cfilipov** [comment]
@ANGOmarcello Your VoIP branch has been working very reliably for me, are you planning on merging that into master to pushing to upstream anytime soon?

**Comment by tjaadvd** [comment]
I have been using it for a couple of days and it's doesn't always automatically change the color. However, battery usage is low since it doesn't show up in the list of apps with the highest usage.

**Comment by tjaadvd** [comment]
Correction: it does seem to work, only sometimes it takes a little time to automatically change.

**Comment by lars06** [comment]
I have the exact same issue! Automatic changing has never worked for me. I've left it all day a few times and it remains on even when it's supposed to be off. Any way this can be fixed?
