### ISSUE TITLE
Readme could use more information about license/permissions

### ISSUE THREAD

**Issue by brittag** [thomasfinch/GammaThingy#6]
Hi Thomas! To help prevent further confusion and misuse, I'd suggest adding some more information to your readme, pretty much along the lines of your [recent Reddit comment](https://www.reddit.com/r/jailbreak/comments/3nlx6o/upcoming_flux_without_jailbreak/cvph92x), such as: that you are intentionally retaining copyright for this code, which means that people may not redistribute it (as code or in compiled form) without your permission; that this project has no relationship to the authors of f.lux; that you recommend people get in contact with the authors of f.lux before releasing related work, since they are nice cool people; and so on.

**Comment by thomasfinch** [comment]
I've added more detail, thank you for bringing this up. I really should have done this from the beginning.
