### ISSUE TITLE
Crash when enabling GammaThingy.

### ISSUE THREAD

**Issue by airportextreme** [thomasfinch/GammaThingy#60]
App is crashing when checking "Enabled".

Crash reports below.

Running iOS 9.2 on iPhone 6S.

This is very similar to crash in GammaThingy fork GoodNight reported [here](https://github.com/anthonya1999/GoodNight/issues/68).

**Comment by AkiTx** [comment]
I have the same problem, I think it is because "IOMobileFramebufferGetGammaTable" changed in iOS 9.2

**Comment by thomasfinch** [comment]
That's not it, I'm having the same problem and I'm still on 9.0.2.
Something changed with all the pull requests I accepted between about
September and now and I'm looking into fixing it.

**Comment by hbarn** [comment]
I found enabling app groups capability and fixing all code signing issues related thereto resolved the issue in the forked version.
