### ISSUE TITLE
No IOMobileFramebuffer

### ISSUE THREAD

**Issue by Spamm3r** [thomasfinch/GammaThingy#62]
ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/PrivateFrameworks'
ld: framework not found IOMobileFramebuffer
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tjaadvd** [comment]
I think im having the same error.

**Comment by Spamm3r** [comment]
bump, still have same error

**Comment by jevinskie** [comment]
Xcode 7.something stopped bundling private frameworks in the iOS SDK. Try getting IOMobileFramebuffer using https://github.com/npupyshev/dt.fetchsymbols

**Comment by thomasfinch** [comment]
The latest commit changes the project to use dynamic instead of static linking, this problem should be gone now.
