### ISSUE TITLE
Not obsolete for people with older ipad/ipod/iphone

### ISSUE THREAD

**Issue by dantahoua** [thomasfinch/GammaThingy#63]
I just discover with iOs 9.3 beta 5 that the Redshift option is not available on my first generation ipad mini!!!! Seems it will not be available on any older 32bit tablet/phone because of a performance issue!!! I never add performance issue with Flux or Gammathingy... Apple marketing...

**Comment by bretth18** [comment]
I don't really see why this is being opened as an issue.

**Comment by dantahoua** [comment]
Sorry, it was just a comment but I don't know how to make just a comment in GitHub without opening an issue. I also wanted to be sure such project do not fall into deprecated stuff as a lot of people still own "old" iOS device...

**Comment by kman14367** [comment]
bretth18 It is sort of an issue with the README.md file, and I agree with dantahoua; it is very useful to those with older devices and I don't want it to become deprecated and dead, since the sideload version of f.lux is very buggy.

**Comment by thomasfinch** [comment]
I just updated the readme file to make a note of this.
