### ISSUE TITLE
Automatic change of color

### ISSUE THREAD

**Issue by tymmej** [thomasfinch/GammaThingy#9]
Would it be possible to include automatic change of color based on user location?
[solar.c](https://github.com/jonls/redshift/blob/master/src/solar.c) from redshift source (GPLv3) should help in implementation of this function.

**Comment by CasperCLD** [comment]
Yes. Awesome idea! I'll look into this. Is it okay if I add this via pull request @thomasfinch ?

**Comment by tymmej** [comment]
No problem.
I can also link my own code to change brightness of computer screen using solar.c: https://github.com/tymmej/brightness/blob/master/brightness.c
So basically use solar_elevation() and then calculate_interpolated_value().

**Comment by CasperCLD** [comment]
Cheers! I've made it work. You can check it out [here](https://github.com/CasperCLD/GammaThingy/tree/develop) for the time being. I want to test it a bit before I'll create a pull request for it. If you want to test it as well, that would be awesome!

**Comment by moshesiegel** [comment]
I've got it running on my 6, I'll report back later tonight. I'm assuming
enabled should be On, time based Off, location On?

**Comment by CasperCLD** [comment]
That's great! All correct except 'Enabled' should be OFF. We might want to change the name of this label to 'manual' as it overrides auto changing behaviour.

**Comment by moshesiegel** [comment]
If the expected result was location based sundown detection and automatic turn on, it didn't work for me. 

I had enabled and time based off, allows location access and it's about 90min past sunset here. 

On Oct 11, 2015, at 9:30 AM, Casper <notifications@github.com> wrote:

That's great! All correct except 'Enabled' should be OFF. We might want to change the name of this label to 'manual' as it overrides auto changing behaviour.

**Comment by abdulkar-im** [comment]
Be awesome if this could get added to GoodNight too!

**Comment by ANGOmarcello** [comment]
Im not even sure if GoodNight is legal.

**Comment by ANGOmarcello** [comment]
The developer stole @thomasfinch code and instead of contributing wrapped it up with an other name and icon.

**Comment by abdulkar-im** [comment]
Seriously?! *deleted

**Comment by CasperCLD** [comment]
This can be closed.
